# https://github.com/marketplace/actions/create-pr-from-one-branch-against-another-branch

name: upmerge

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create PR
        uses: poorva17/create-pr-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_BRANCH: main
          BASE_BRANCH: dev
