name: Automate
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
jobs:
  automate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: toshimaru/auto-author-assign@v1.3.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}