on:
  push:
    branches:
      - main
      - qa
      - dev
      - dev-qa
      - 'release/**'
      - 'hotfix/**'
      - 'feature/**'
name: frontend-build
defaults:
  run:
    working-directory: Front-end
jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.4.2]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install all of dependencies
        run: |
          npm set-script prepare ""
          npm ci --no-optional
      - name: Build
        run: npm run build
